### PR TITLE
add requirements file and exit properly

### PR DESCRIPTION
**Pull request by sillychipmunk**
- [x] keep red triangle always on top
- [x] add requirements file
- [x] format with black

### CODE REVIEW

**Comment by sillychipmunk** [comment]
@x-actly if you like i can take a look into this repo as collaborator and see if i can merge it with mining bot at some point

**Comment by x-actly** [comment]
Sure, I'll add you shortly, but then I'll make the repo invisible again.

**Comment by sillychipmunk** [comment]
@x-actly can make a mini org for this. x-actly-org 😆 hehe .. personal repos are always vulnerable. But hey you decide man 💪

**Comment by x-actly** [comment]
@sillychipmunk Are you still able to fork this repo while it's invisible?

**Comment by sillychipmunk** [comment]
no issues, not needed though, but nice to keep a copy

**Comment by sillychipmunk** [comment]
had to delete previous

**Comment by x-actly** [comment]
My mistake, I didn't know that! I'll make it public again! Sorry.

**Comment by sillychipmunk** [comment]
Oh its only 1 public repo with collaborators? And other ones you cant add collaborators to? I didnt know that. Anyway this functionality will be taken into the mining bot propably, at some time. We'll see.

**Comment by x-actly** [comment]
The repo was actually just there to see how image recognition and its reliability work. The script at least served its purpose back then and always safely warped the Ishtar to the station whenever someone entered the system who shouldn't be there.

**Pull request merged**
